### ISSUE TITLE
raiz

### ISSUE THREAD

**Issue by mobybr-1** [IvetC01/IvetC01.github.io#12]
**Descripción:** 
Obtener la raíz de un numero. 

**Mockup:** 
![image](https://user-images.githubusercontent.com/105674700/221225016-0f9b79e4-f11e-4b5f-aa33-a32b22ae6056.png)

**Pruebas:** 
- [ ] Contener el título "Raíz". 
- [ ] Visualizar el nombre del integrante. 
- [ ] Resultado de la raíz de un número.

**Comment by IvetC01** [comment]
.
