### ISSUE TITLE
potencia

### ISSUE THREAD

**Issue by mobybr-1** [IvetC01/IvetC01.github.io#13]
**Descripción:** 
Obtener la potencia de un número. 

**Mockup:** 
![image](https://user-images.githubusercontent.com/105674700/221225738-59e08233-5828-4088-9db1-71b0c856d01d.png)

**Pruebas:** 
- [ ] Deberá contener el título "Potencia". 
- [ ] Nombre del integrante. 
- [ ] Resultado de la potencia un número.

**Comment by IvetC01** [comment]
.
