### ISSUE TITLE
Resta

### ISSUE THREAD

**Issue by IvetC01** [IvetC01/IvetC01.github.io#5]
**Descripción:** 
Calculo de la resta de 2 números. 

**Mockup:** 
![image](https://user-images.githubusercontent.com/105674700/218502925-a71e49cf-2366-4844-8b3a-4f7248efd6e4.png)

**Pruebas:** 

- [ ] Deberá visualizar título "Resta". 
- [ ] Deberá visualizar nombre del responsable. 
- [ ] Deberá visualizar ejemplo de resta.

**Comment by mobybr-1** [comment]
Operacion resta <br>

Realizado por Ivet C

x = 0.14 <br>
y = 3.00 <br>
z = 3.14 <br>
